name: Claude PR Review (Advanced)

permissions:
  contents: write
  issues: write
  id-token: write
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '@claude')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude') && github.event.issue.pull_request) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
    uses: NandosUK/.github/.github/workflows/claude-reusable.yml@main
    with:
      # Optional: Override timeout (default is 60 minutes)
      timeout_minutes: '45'
      
      # Optional: Override max conversation turns (default is 5)
      max_turns: '3'
      
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      CLAUDE_APP_ID: ${{ secrets.CLAUDE_APP_ID }}
      CLAUDE_APP_PRIVATE_KEY: ${{ secrets.CLAUDE_APP_PRIVATE_KEY }}