name: Claude PR Review (Advanced)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]  
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened, synchronize]
    branches: [main, develop]

jobs:
  claude-review:
    # Advanced conditional logic
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '@claude-auto'))

    uses: NandosUK/.github/.github/workflows/claude-reusable.yml@main
    with:
      # Custom organization instructions URL
      instructions_url: 'https://raw.githubusercontent.com/NandosUK/.github/main/INSTRUCTIONS.md'
      
      # Optional: Override timeout (default is 60 minutes)
      # timeout_minutes: '45'
      
      # Optional: Override max conversation turns (default is 5)
      # max_turns: '3'
      
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      CLAUDE_APP_ID: ${{ secrets.CLAUDE_APP_ID }}
      CLAUDE_APP_PRIVATE_KEY: ${{ secrets.CLAUDE_APP_PRIVATE_KEY }}

  # Optional: Run additional checks before Claude review
  pre-claude-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for large files
        run: |
          # Skip Claude review if PR has very large files
          large_files=$(find . -name "*.js" -o -name "*.ts" -o -name "*.py" | xargs wc -l | awk '$1 > 1000 {print $2}' | head -5)
          if [ -n "$large_files" ]; then
            echo "::warning::Large files detected, Claude review may timeout"
            echo "Large files: $large_files"
          fi
          
      - name: Security scan
        run: |
          # Basic security checks before Claude review
          if grep -r "password\|secret\|key" --include="*.js" --include="*.ts" . | grep -v node_modules; then
            echo "::warning::Potential secrets detected, Claude will focus on security"
          fi

  # Optional: Post-review actions
  post-claude-actions:
    runs-on: ubuntu-latest
    needs: claude-review
    if: always() && github.event_name == 'pull_request'
    steps:
      - name: Update PR labels
        uses: actions/github-script@v6
        with:
          script: |
            // Add label to indicate Claude has reviewed
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['claude-reviewed']
            });
            
      - name: Notify team
        if: contains(github.event.pull_request.labels.*.name, 'security-review-needed')
        run: |
          echo "Security-sensitive PR reviewed by Claude"
          # Add webhook notification to Slack, etc.