# Put this in: NandosUK/.github/.github/workflows/claude-organization-wide.yml
name: Claude Code Review (Organization-wide)

on:
  # This workflow runs on ALL repositories in the organization
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: read

jobs:
  claude-review:
    # Only run if @claude is mentioned
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_APP_PRIVATE_KEY }}
          repository: ${{ github.repository }}

      - name: Claude Code Action
        uses: anthropics/claude-code-action@main
        with:
          trigger_phrase: "@claude"
          timeout_minutes: "60"
          max_turns: 5
          github_token: ${{ steps.app-token.outputs.token }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:
          ORGANIZATION: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.event.repository.name }}
          TARGET_REPOSITORY: ${{ github.repository }}
