name: Claude Code Review

on:
  workflow_call:
    secrets:
      ANTHROPIC_API_KEY:
        required: true
      CLAUDE_APP_ID:
        required: true
      CLAUDE_APP_PRIVATE_KEY:
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_APP_PRIVATE_KEY }}

      - name: Claude Code Action
        uses: anthropics/claude-code-action@main
        with:
          trigger_phrase: "@claude"
          timeout_minutes: "60"
          max_turns: 10
          github_token: ${{ steps.app-token.outputs.token }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:
          ORGANIZATION: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.event.repository.name }}